### ISSUE TITLE
Multiple Feature Requests

### ISSUE THREAD

**Issue by endervad** [TexTools/FFXIV_TexTools_UI#133]
Hello. I'm sorry in advance if my requests are too big. Tell me also if it's better to separate them into several GitHub issues for organization purposes.
A bit of background: I translate the game into Russian and distribute the mod as TexTools modpack. I use "Import Raw File" feature to import EXD files that I prepare in advance with my own scripts.
I'd like to ask to expand Import and Export Raw File features. To be exact:

1. Being able to import multiple raw files/folders in one go.
For example, by importing folder/file structure relative to a specified folder. User chooses the "root" folder first (which is going to be / for FFXIV), then inside this folder they choose the files/folders they want to import.

2. Extract Raw Files - Being able to list all of the game files and folders in a tree-like structure
3. ...And to mass extract files/folders using checkboxes.
I ask these two features since the only GUI program that is capable of doing that is FFXIV Explorer. Unfortunate it's very outdated and it misses a lot of the files. Right now it's possible to extract any file in TexTools by specifying a path, but yet again there's currently no GUI program (or at least I don't know one but I've searched) that could at least list the game's files structure. I know that there are libraries that could do this, like TexTools' one or xiv-datamine's, but I'm not a programmer and I couldn't make sense of how to use it.

4. This one is a minor one but it would be awesome to be able to work with all of the game's textures from all folders. E.g. we changed FFXIV's font a little bit to adapt for Russian, and to import these textures I needed to:
* Import DDS file over a random texture
* Extract this file as raw without Type-2 decompression
* Import the extracted file as raw into the correct path without Type-2 compression

I'll understand if it gets declined because I ask too much and I can't really help with the code, but these improvements would help immensely with creating the mod.

**Comment by ghost** [comment]
I have a ghetto version of the EXE on [my discord](https://discord.gg/UdY9vae) that allows batch import of DDS textures. It requires the path defined by FFXIV Explorer. 
It's a bit hacky so I can't really do it as a pull request for the main TexTools repository, but you're welcome to download it. OFC if any of the devs want my spaghetti pls let me know.

I am sort of working on batch extract with textools, but unfortunately it's a little more complicated.

**Comment by endervad** [comment]
Thanks @emarron , this basically solves my 4th point then, so I'll definitely keep it in mind whenever I need it :) Still though 99% of the time I currently need batch import of raw EXD files for my translation.
Also, to the TexTools devs: I'm up to make a Russian translation of the program. It's the least I can do since I can't help with coding.

**Comment by Lunaretic** [comment]
- Mass Import
Being worked on as part of file-watcher imports, etc.

- Tree  View
Unlikely to happen, due to the hash nature of the game file structure, and TT not keeping a brute-forced list a-la xivexplorer.  Would have to load the list directly from XivExplorer, in which case.. Just use that.

- Mass Extract by folder
See above, not viable.

- Extract this file as raw without Type-2 decompression
Already implemented for some time, but you can now also extract any file type in compressed or uncompressed format, in Dawntrail builds/3.0

- Import DDS file over a random texture / Import Type 2 Files
Resolved in Dawntrail builds.  Standard file import can now import compressed, uncompressed, and normal human files, agnostic-ally.

Closing as resolved as all of these are either implemented, in-process, or will-not-fix.
