### ISSUE TITLE
Could not find offset for chara/xls/charadb/equipmentdeformerparameter/c1701.eqdp

### ISSUE THREAD

**Issue by gousanriku** [TexTools/FFXIV_TexTools_UI#137]
---------------------------
Error Importing Mods
---------------------------
There were errors importing some mods.

An error occured when attempting to expand the metadata entries.

Error:Could not find offset for chara/xls/charadb/equipmentdeformerparameter/c1701.eqdp
---------------------------
OK   
---------------------------

HI! After I updated Chinese FFXIV 5.58 today, I get this error message when I install any mod. Please tell me what to do? Thank you very much!

**Comment by KoraLyn** [comment]
The latest version of TexTools has been incompatible with the Chinese and Korean client since the launch of Endwalker. Going to leave this issue open for those looking for an explanation for their errors. You can still use [an older version of TexTools](https://github.com/TexTools/FFXIV_TexTools_UI/releases/tag/v2.3.6.2) with the non-international clients.

**Comment by Squall-Leonhart** [comment]
This can now be closed
