### ISSUE TITLE
Textures Tab: Missing Hair Texture Listings

### ISSUE THREAD

**Issue by igniscitrinus** [TexTools/FFXIV_TexTools_UI#22]
In the Texture Viewer, a number of races are missing texture listings for hair meshes:
![image](https://user-images.githubusercontent.com/14958008/102235454-a2d7ee00-3ef2-11eb-950a-6b313bf07daa.png)
![image](https://user-images.githubusercontent.com/14958008/102235281-76bc6d00-3ef2-11eb-9b14-70155941da99.png)

The textures load in the Model Viewer and export as intended.

At a glance, the affected numbers are between, and excluding, 61 and 201 for the following races:
Hyur Highlander M/F
Elezen M/F
Roegadyn M/F
Lalafell M/F
AuRa M/F (AuRa M has no hair numbers over 201)

Miqote M - between 114 and 201 affected
Miqote F - between 115 and 201 affected

**Comment by KoraLyn** [comment]
These textures aren't actually missing in the sense that they don't exist. A lot of materials for these hair models are shared by multiple races. Admittedly this isn't very clear for hair like it is for equipment so that's a possible point of improvement. You can tell what materials are used by the model by clicking on the magnifiying glass to open the `File Info` window. In the bottom right listed under `Child Files` you can see the materials used by the model. In the picture below I've taken male highlander's hair 116 as an example and you can see it actually uses the male midlander's material and therefore textures.
![image](https://user-images.githubusercontent.com/59175928/102283758-4f39c480-3f33-11eb-99a7-6697bb9cf284.png)

**Comment by igniscitrinus** [comment]
I hadn't thought to check the file info for the actual location of the textures, that makes a lot of sense in retrospect.
Many thanks for the clarification.
