### ISSUE TITLE
[Feature Request] Treat opening modpacks/.ttmp2 files as using the "Import Modpacks" option

### ISSUE THREAD

**Issue by ivalith** [TexTools/FFXIV_TexTools_UI#67]
I'd like to request that opening/launching a modpack be treated the same way as using the "Import Modpacks" option within textools when textools is already open as an adjustment to the program closing itself. If I've got textools open in order to check a model already it's really inconvenient to have it close, import the mod and then have to re-open textools again afterward and go back to where I already was. I thought this was necessary until realizing the import modpacks option can do this and it'd be convenient for this to be the case when opening a modpack as well.

**Comment by KoraLyn** [comment]
It's not as simple as you make it out to be but I understand the desired behaviour. The obvious workaround is just to use the menu instead of importing by file association which, to me, seems like a very minor inconvience.

Could be solved through interprocess communication by handling the import in the existing process instead of force closing existing processes and handling the import in the newly launched process.

**Comment by Lunaretic** [comment]
This is likely never happening due to how convoluted it would be (for minimal benefit), since we'd have to write a separate handler application to be the actual default file handler that then launches TT with args if not open or does some kind of IPC communication to TexTools to notify it to launch a new modpack install (assuming it would even be in a state to do so).
